---
title: "Assignment 2"
output: html_document
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(WDI)
library(ggplot2)
```

## Research Question
  Twenty Years since the end of Apartheid: Did the collapse of Apartheid play a significant role in reducing racial and social inequality in South Africa? Is post-apartheid South Africa better off or worse off than during the apartheid era? 

## Hypothesis
  Since the end of apartheid and begnning of democracy in South Africa, socio-economic problems associated with white-supremacy, such as racial imbalance in income distribution, educational dispartiy, unemployment rate, and crime rate, has been improving, leading to successful transition and development of the country.

## Justification for the research 
  After the collapse of the apartheid, South Africa held its very first historic democratic election in 1994 and announced to the world a new beginning of the country. By electing Nelson Mandel as the president of South Africa, people of all races in the country hoped to see democratic policies which would alleviate poverty and social inequality. Now that over 20 years have passed, the country has been asked for its transition whether or not Mandela's democratic vision has been fulfilled, especially in terms of non-racial, equal, and progressive political economic development. Our research, therefore, aims to analyze the country's performance in meeting the targets and delivering policies by making comparisons of various social features before and after the apartheid. 
This research is interesting because not only we deal with unique country, South Africa, where experienced very controversial history of racial segregation and white supremacy, but also we evaluate its democratic development and expectation based on several social indicators.

  First of all, as a newly industrialized country, South Africa is now classified as an upper-middle-income economy where is now seen as one of the fastest growing economies from 2000 to 2013. Besides, its economy is the second-largest on the continent with a middle purchasing power parity, maintaining significant regional economic influence. Through making political and economic improvements since the polls in 1994, South Africa truly have gained international value and taken a growing role in the global economy as a trading partner. In terms of international political roles, South Africa has been playing a significant role as a conflict mediator over the last decade, especially in Burundi, the Democratic Republic of Congo, and Zimbabwe. Also, the country is a member of the G77, G20, G8+5, the South African Development Community, World Trade Organization, and International Monetary Fund. Likewise, at the macro-level, South Africa successfully scored global economic and political roles and gave a further impression of optimism for growth by attracting global firms and investment based on business-friendly environment and well-connected infrastructure, standing as a beacon for African development in the 21st century. Despite of such positive changes, however, South Africa is still suffering from a high rate of poverty and unemployment within its society. Moreover, a quarter of the population is living with less than US $1.25 per day and the country was ranked in the top 10 countries in the world for income inequality according to the Gini coefficient. Therefore, we believe that, in terms of political and economic context, it will be interesting to analyze the country to find out whether sound performances of the macro-economy have successfully translated into positive social changes and have overcome the apartheid legacy of racial segregation, poverty and inequality. Based on the findings, we can also come up with policy recommendations for the sake of creating a more equal and fair society and of increasing the governance capacity for mutual benefits within the global economic world.   
  
  Secondly, we believe that it is worth researching about the apartheid, analyzing its legacy, and any changes in post-apartheid, in terms of the historical and social context, since the policy itself was very controversial and unjust. Even before the official apartheid began, racial segregation and white supremacy was a central aspects of South African policy because of the 1913 Land Act, which forced black Africans to live in reserves. In 1948, South Africa's all-white government began enforcing policies of racial segregation with the system of apartheid. Under the rule of apartheid, nonwhite South Africans not only were forced to live in segregated neighborhoods from whites but also had to use separate restaurants, and other public facilities. Being at the very bottom of the social strata, black people were taken away of their citizenships, separated from public education, medical care, and all other public services. Moreover, they found jobs on white-owned mines, farms, or as servants for white households while being treated as inferiors. As a result, Apartheid sparked several significant internal resistance, uprisings, and protests organized by different kinds of sectors of local societies. One of the most popular internal resistance took place in 1976 in Soweto, a black township outside Johannesburg, when thousands of black children demonstrated against the Afrikaans language requirement for black African students. Since this uprising, South Africa's brutal apartheid policy drew more and more international attention to the country, and finally, the United Nations stepped up in the 1980s to end apartheid by utilizing economic sanctions and placing trading embargos against South African products. By the early 1990s, both internal and external efforts began to be effective as a series of negotiations started to dismantle apartheid. As both President of the Youth League and deputy ANC (African National Congress) President, Nelson Mandela was the one who intensified the grassroots resistance efforts despite of his multiple imprisonments. Apartheid officially ended in 1994 and Nelson Mandela became the first black and freely elected president of South Africa. During his presidency, Mandela established majority rule, guaranteed minority rights and freedom of expression, and devoted to improve employment, housing and basic public services including health care. However, as abovementioned already, the great expectation since Nelson Mandela, according to several researches, has been in crisis due to the failure of policy implementation and governance corruption over the last 20 years. As studying historical and social aspects of South Africa with respect to their brutal and immoral apartheid policy for decades, we would like to analyze and verify whether the South African income distribution and general human development have improved in terms of alleviating poverty and inequality.This research is not only interesting but also meaningful since it embeds our sincere hope to see the successful transition of newly democratized country, South Africa, from the society with racism and white-supremacy to one with more equal and sustainable livelihoods for all.   

#Literature Review 
1.How South Africa has changed since Nelson Mandela's release - the Guardian https://www.theguardian.com/world/datablog/2013/dec/06/how-south-africa-changed-since-nelson-mandelas-release-prison-1990

 --> Overview: This is a Datablog article from The Guardian, which provides graphs related to Economic growth, Trade, Migration, Life expectancy, and Living conditions in South Africa over the last decades. The article also allows readers to directly access to the data so that readers can see the figures and share their views. According to the data provided by the article, GDP per capita has risen since the year of 1990, spending on healthcare has steadily improved from 2.9% in 1995 to 3.4% in 2005, and living conditions in terms of sanitation facilities has made improvements over the last decade. @WB @SASA

2.One Kind of Freedom: Poverty Dynamics in Post-Apartheid South Africa- World Development Volume 29, Issue 12, December 2001, Pages 1987-2006 http://www.sciencedirect.com/science/article/pii/S0305750X01000894#

 --> Overview: This research paper explores whether the legacy of apartheid in terms of inequality and human insecurity has been superseded by looking at the dynamics of post-apartheid income distribution based on the data from national household surveys. The analysis of this research paper argues that the end of apartheid has thus far at least proven to be only one kind of freedom because material well-being of significant numbers of South Africans has been headed downward and caught in a poverty trap. As a result, a large number of South Africans have been unable to take advantage of the liberalized post-apartheid environment. @mona

3.	Income and Non-income Inequality in Post-Apartheid South Africa: What are the Drivers and Possible Policy Interventions? - Development Policy Research Unit, August 2009 http://www.cde.org.za/wp-content/uploads/2013/02/The%20Next%20Decade.pdf#page=95

 --> Overview: This literature of study identifies the drivers of the reproduction of inequality in post-apartheid South Africa and examines possible policy choices in order to mitigate the impact of increased inequality. This paper argues, based on the analysis of data of Income and Expenditure surveys conducted in 1995, 2000, and 2005, that there had a continuous increase in inequality, strongly indicating that South African is now the one of the most consistently unequal economy in the world. We can use this literature to support our later argument that wage inequality among races can be the main contributor to the growing income inequality. @michael
 
 4.	Poverty and Well-being in Post-Apartheid South Africa: An Overview of Data, Outcomes and Policy - Development Policy Research Unit (2005) https://papers.ssrn.com/sol3/papers.cfm?abstract_id=982805
 
--> Overview: This study provides an overview of poverty and well-being of South African during the first decade of post-apartheid. Focusing on the poverty and policy availability for future, this analysis paper argues that the first ten years after the end of Apartheid has rather displayed increase in income inequality and unemployment rates. The study also stated that the analysis observed the declining share of rural poverty due to increased migration and urbanization.@deve1

5.	Crime and local inequality in South Africa - Journal of Development Economics (December 2003) http://www.sciencedirect.com/science/article/pii/S0304387804001117

-->	Overview: This research literature examines the effects of local inequality and violent crime in South Africa in the post-apartheid era with findings that inequality actually lead to crime in general. By using data on crime and estimates of welfare measured by all police precincts in South Africa, the study argues that while inequality between racial groups does not appear to be too important with respect to crime, racial heterogeneity is highly correlated with all types of crime. As a result, in order to reduce economic inequalities and help decrease property crime levels, it suggested to improve the distribution of income not only both within and between racial groups but also between neighborhoods within a local administration.@deve2 

6.	Poverty and Inequality Dynamics in South Africa: Post-apartheid Developments in the Light of the Long-Run Legacy- Southern Africa Labour & Development Research Unit, University of Cape Town (January 2007) http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.605.3877&rep=rep1&type=pdf

--> Overview: This research literature provides the evidence based on several data gathered, which shows a very high inequality society with a strong racial component to this inequality in South Africa in the post-Apartheid era. Arguing that the bottom half of the income distribution and poverty has been dominated by these black South Africans, the study concludes by suggesting the government to improve the education and health system and develop labor market behaviors.@SAL


## Research Methodologies
In order to answer the questions posed based on our hypothesis, we are going to compare various socio-economic indicators before and after 1994, the year Apartheid officially abolished.

We will investigate following indicators after the abolishment of apartheid.

  1, racial imbalance in income distribution
  
  2, educational disparty
  
  3, crime rate

## Data sources
We will use following data sources to conduct our research

  1, WorldBank

  2, United Nations Development Programme

  3, Statistics South Africa

  4, US Census Bureau


# References
